commit_message: 'RPMTW 新翻譯更新 %original_file_name%'
append_commit_message": false

files:
  - source: 1.12/assets*
    ignore:
      - Add-on
      - zh-TW
    translation: '%original_path%/%file_name%.%file_extension%'
