commit_message: "\U00E696B0\U00E7BFBB\U00E8ADAF\U00E69BB4\U00E696B0"
files:
  - source: 1.17/assets*
    ignore:
      - Add-on
      - zh-TW
    translation: '%original_path%/%file_name%.%file_extension%'
