modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="ttigraas"
version="1.1.2"
displayName="TTIGRAAS"
credits="TTIGRAAS"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MinhEragon"

[[dependencies.ttigraas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




