name: Build Pack ( 1.12 )

on:
  push:
    branches: [Translated-1.12]
    paths:
      - "zh-TW/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Translated-1.12
      - uses: actions/checkout@v2
        with:
          ref: main
          path: "main"
      - uses: dart-lang/setup-dart@v1

      - name: 安裝依賴項
        run: |
          ls
          cd main/Scripts
          dart pub get

      - name: "將 Json 轉換為 Lang"
        run: |
          dart run ./main/Scripts/bin/main.dart --action json_to_lang --gameVersion 1.12.2 --dirGameVersion 1.12

      - uses: papeloto/action-zip@v1
        with:
          files: zh-TW/1.12 Add-on/1.12/
          dest: RPMTW-1.12.zip
      - name: "提交檔案"
        continue-on-error: true
        run: |
          git config --global user.email "rpmtw666@gmail.com.com"
          git config --global user.name "翻譯包更新機器人"
          git add ./RPMTW-1.12.zip
          git commit -m "更新翻譯包"
          exit 0

      - name: "推送變更"
        continue-on-error: true
        run: |
          git push
          exit 0
