name: Build Pack ( 1.17 )

on:
  push:
    branches: [Translated-1.17]
    paths:
      - "zh-TW/**"
      - "Add-on/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Translated-1.17
      - uses: papeloto/action-zip@v1
        with:
          files: zh-TW/1.17 Add-on/1.17/
          dest: RPMTW-1.17.zip

      - name: "推送變更"
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.event.inputs.ref }}
          commit-message: "更新翻譯包"
          force-add: true
          files: ./RPMTW-1.17.zip
          name: RPMTW Bot
          email: rpmtw666@gmail.com
          rebase: true
