name: Build Pack ( 1.12 )

on:
  push:
    branches: [Translated-1.12]
    paths:
      - "zh-TW/**"
      - "Add-on/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Translated-1.12

      - name: "將 Json 轉換為 Lang"
        uses: RPMTW/Translation-Scripts@main
        with:
          action: "json_to_lang"
          gameVersion: "1.12"

      - uses: papeloto/action-zip@v1
        with:
          files: zh-TW/1.12 Add-on/1.12/
          dest: RPMTW-1.12.zip

      - name: "推送變更"
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.event.inputs.ref }}
          commit-message: "更新翻譯包"
          force-add: true
          files: ./RPMTW-1.12.zip
          name: RPMTW Bot
          email: rpmtw666@gmail.com
          rebase: true
