name: CI
 
on:
  push:
    branches: [ Translated-1.17 ]
    paths:
    - 'zh-TW/1.17/**'
    - 'Add-on/1.17/**'
    - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1 #zipped file 1.17
        with:
          files: zh-TW/1.17 Add-on/1.17/
          dest: RPMTW-1.17.zip
      - name: "提交檔案"
        continue-on-error: true
        run: |
          git config --global user.email "rpmtw666@gmail.com.com"
          git config --global user.name "翻譯包更新機器人"
          git add ./RPMTW-1.17.zip
          git commit -m "更新翻譯包"
          exit 0
        
      - name: "推送變更"
        continue-on-error: true
        run: |
          git pull
          git push
          exit 0
