name: CI
 
on:
  push:
    branches: [ Translated ]
    paths:
    - 'zh-TW/1.16/**'
    - 'Add-on/1.16/**'
    - '.github/workflows/**' 
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1 #zipped file 1.16
        with:
          files: zh-TW/1.16 Add-on/1.16/
          dest: RPMTW-1.16.zip
      - name: "提交檔案"
        run: |
          git config --global user.email "rpmtw666@gmail.com.com"
          git config --global user.name "翻譯包更新機器人"
          git add ./RPMTW-1.16.zip
          git commit -m "更新翻譯包"
        
      - name: "推送變更"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}