name: "Mod Lang File Downloader"

on:
  workflow_dispatch:
  
env:  
  ModID: ${{ secrets.MODID }} 
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: |
       cd ${{ github.workspace }}/Spider
       npm i
       node DownloadMod.js
  
    # - run: node ${{ github.workspace }}/Spider/index.js
    - name: "提交檔案"
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@users.noreply.github.com'
          @"
          protocol=https
          host=github.com
          username=github-actions[bot]
          password=${{ secrets.GITHUB_TOKEN }}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git add .
          git commit -m "新增原始語系檔案"
          git push origin HEAD:${{ github.ref }}
      shell: pwsh
