name: UpdateLang

on:
  schedule:
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: Original-1.12
            gameVersion: "1.12.2"
            dirGameVersion: "1.12"
          - ref: Original
            gameVersion: "1.16.5"
            dirGameVersion: "1.16"
          - ref: Original-1.17
            gameVersion: "1.17.1"
            dirGameVersion: "1.17"
      max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.ref }}

      - name: "更新原始語系檔案"
        uses: RPMTW/Translation-Scripts@main
        with:
          action: "update_lang"
          gameVersion: ${{ matrix.gameVersion }}
          dirGameVersion: ${{ matrix.dirGameVersion }}

      - name: "推送變更"
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ matrix.ref }}
          commit-message: "更新原始語系檔案"
          force-add: true
          files: ./${{ matrix.dirGameVersion }}/assets
          name: 原始語系檔案更新機器人
          email: rpmtw666@gmail.com.com
          rebase: true
